#pragma once
#include <3ds/types.h>

// Result values
#define SPI_OUT_OF_RANGE      MAKERESULT(RL_USAGE,     RS_INVALIDARG,   RM_SPI, RD_OUT_OF_RANGE)
#define SPI_NOT_INITIALIZED   MAKERESULT(RL_STATUS,    RS_INVALIDSTATE, RM_SPI, RD_NOT_INITIALIZED)

// Result values, my additions edition:tm:
#define SPI_INTERNAL_RANGE    MAKERESULT(RL_FATAL,     RS_INTERNAL,     RM_SPI, RD_OUT_OF_RANGE)
#define SPI_CANCELED_RANGE    MAKERESULT(RL_FATAL,     RS_CANCELED,     RM_SPI, RD_OUT_OF_RANGE)

#define SPI_INVALID_SELECTION MAKERESULT(RL_PERMANENT, RS_NOTSUPPORTED, RM_SPI, RD_INVALID_SELECTION)
